### ISSUE TITLE
Release 0.1.6

### ISSUE THREAD

**Issue by glemmaPaul** [glemmaPaul/django-taggit-serializer#20]
- [ ] Create tests for partially updating data with the serializer #9
- [ ] Add better docs about input request #18
- [ ] Add contributors to the package #19
- [ ] Add comments to code #21
- [ ] Allow multiple input formats #25
- [ ] Allow multiple output formats #29

**Comment by glemmaPaul** [comment]
Closing this as this is going to be irrelevant
